server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://db/db
    username: spring
    password: boot
  jpa:
    # hibernate:
    #   ddl-auto: update
    properties:
      hibernate:
        "[default_schema]": api_db
      # jdbc:
      #   lob:
      #     "[non_contextual_creation]": true