spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: dba
    password: 46427230
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
