name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout the repo"
      uses: actions/checkout@v3
      
    - name: "Docker login"
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: "Build, tag, and push the Docker image - latest"
      if: ${{ github.ref_name == 'main' }}
      env:
        IMAGE_NAME: ${{secrets.DOCKER_USER}}/api
        IMAGE_TAG: latest
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG
        
    - name: "Build, tag, and push the Docker image"
      if: ${{ github.ref_name != 'main' }}
      env:
        IMAGE_NAME: ${{secrets.DOCKER_USER}}/api
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG
